### ISSUE TITLE
Integer overflow in mintTokens

### ISSUE THREAD

**Issue by whiteHat001** [Cryptaur/cryptaur-contract#1]
There is an integer overflow in mintTokens in line 76
vuln code:
```
    function mintTokens(address _minter, uint _tokens, uint8 _originalCoinType, bytes32 _originalTxHash) public {
        require(msg.sender == cryptaurBackend);
        require(!crowdsaleFinished);
        balanceOf[_minter] += _tokens;  // integer overflow
        totalSupply += _tokens;
        Transfer(this, _minter, _tokens);
        Mint(_minter, _tokens, _originalCoinType, _originalTxHash);
    }
```

result
![image](https://user-images.githubusercontent.com/18191034/42629572-5c540baa-8606-11e8-9dd3-3db78ce9594c.png)
code  address
https://etherscan.io/address/0x88d50b466be55222019d71f9e8fae17f5f45fca1#code

Discovered by zhihua.yao from dbappsecurity.com.cn

**Comment by isvirin** [comment]
Thank you for your attention, but this hole can't be used now, because crowdsaleFinished=true and function can't be called.

**Comment by isvirin** [comment]
> But the crowdaleFinished in your smart contract address code on Ethereum is not true as you said.
I've checked once again. It is TRUE.

**Comment by whiteHat001** [comment]
Sorry for my fault, but I am using your contract code to test on remix and there is an overflow vulnerability. If you ensure that this vulnerability is not affected by this vulnerability, ignore this issue.

**Comment by isvirin** [comment]
Thank you once again for your attention and your report!

**Comment by whiteHat001** [comment]
Thank you very much for your prompt reply. If I find a vulnerability in the future, I will submit it in the first time.
